#define WINDOW_HEIGHT 350
#define WINDOW_WIDTH 350

#define SQUARE_EDGE 350
#define TOTAL_BLOCKS (SQUARE_EDGE / BLOCK) * (SQUARE_EDGE / BLOCK)

#define BLOCK 35
#define GAP 2
#define SNAKE_SIZE BLOCK - GAP


#define TIMER_INTERVAL 200